'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
const read = name => fs.readFileSync(path.join(root, name), 'utf8');
const write = (name, data) => fs.writeFileSync(path.join(root, 'dist', name), data);
fs.mkdirSync(path.join(root, 'dist'), {recursive: true});
let html = read('src/index.html');
html = html.replace('<link rel="stylesheet" href="styles.css">', () => '<style>\n' + read('src/styles.css') + '\n</style>');
for (const name of ['engine', 'app']) html = html.replace('<script src="' + name + '.js"></script>', () => '<script>\n' + read('src/' + name + '.js').replace(/<\/script/gi, '<\\/script') + '\n</script>');
write('index.html', html);
write('taxman-offline.html', html);
write('engine.js', read('src/engine.js'));
for (const name of ['API.md', 'SOURCES.md', 'input.schema.json', 'llms.txt']) write(name, read(name));
write('cli.cjs', read('cli.cjs').replace("require('./src/engine.js')", "require('./engine.js')"));
const assets = ['index.html','taxman-offline.html','engine.js','API.md','SOURCES.md','input.schema.json','llms.txt','cli.cjs'];
const hash = crypto.createHash('sha256').update(assets.map(readName => fs.readFileSync(path.join(root,'dist',readName))).join('')).digest('hex').slice(0,12);
write('sw.js', `'use strict';
const CACHE = 'taxman-' + new URL(self.registration.scope).pathname + '-${hash}';
const ASSETS = ${JSON.stringify(assets)};
self.addEventListener('install', event => { event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS)).then(() => self.skipWaiting())); });
self.addEventListener('activate', event => { event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith('taxman-' + new URL(self.registration.scope).pathname + '-') && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url), scope = new URL(self.registration.scope);
  if (url.origin !== scope.origin || !url.pathname.startsWith(scope.pathname)) return;
  event.respondWith(fetch(event.request).catch(() => caches.open(CACHE).then(cache => cache.match(event.request, {ignoreSearch:true}).then(hit => hit || (event.request.mode === 'navigate' ? cache.match('index.html') : Response.error())))));
});
`);
console.log('Built dependency-free distribution in dist/ (' + Buffer.byteLength(html) + ' byte standalone page).');
